apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  backoffLimit: 1
  template:
    metadata:
      name: test-job
    spec:
      containers:
        - name: job
          image: bash
          command:
            - echo
            - 'Hello World'
      restartPolicy: Never

